/// Hand-rolled completion-script generators for bash / zsh / fish.
/// Kept tiny and command-list-driven so adding a new subcommand only requires
/// extending `commands` below — every shell picks it up automatically.
public enum CompletionsFormatter {
    /// Canonical list of subcommand names. Must stay in sync with CLIRunner's
    /// dispatch switch — there's a unit test that verifies the overlap.
    public static let commands: [String] = [
        "list", "get", "modes",
        "mode", "main", "mirror", "unmirror", "move", "rotate",
        "flip", "flip-overlay", "pip",
        "switch", "cycle", "brightness",
        "save", "restore", "profiles",
        "watch", "workshop", "daemon",
        "doctor", "sleep", "virtual",
        "completions", "manpage",
        "version", "help",
    ]

    public static func zsh() -> String {
        let words = commands.joined(separator: " ")
        return """
        #compdef wdm
        # zsh completion for wdm — generated by `wdm completions zsh`.

        _wdm() {
            local -a subcommands
            subcommands=(\(words))
            if (( CURRENT == 2 )); then
                _describe 'subcommand' subcommands
            else
                _files
            fi
        }

        _wdm "$@"

        """
    }

    public static func bash() -> String {
        let words = commands.joined(separator: " ")
        return """
        # bash completion for wdm — generated by `wdm completions bash`.
        _wdm() {
            local cur prev words cword
            COMPREPLY=()
            cur="${COMP_WORDS[COMP_CWORD]}"
            if [ "$COMP_CWORD" -eq 1 ]; then
                COMPREPLY=( $(compgen -W "\(words)" -- "$cur") )
            else
                COMPREPLY=( $(compgen -f -- "$cur") )
            fi
            return 0
        }
        complete -F _wdm wdm

        """
    }

    public static func fish() -> String {
        var lines: [String] = [
            "# fish completion for wdm — generated by `wdm completions fish`.",
            "complete -c wdm -f"
        ]
        let argList = commands.map { "'\($0)'" }.joined(separator: " ")
        lines.append("complete -c wdm -n '__fish_use_subcommand' -a \(argList)")
        return lines.joined(separator: "\n") + "\n"
    }
}
